[tools]
rojo = 	{source = "rojo-rbx/rojo", 			version = "7.1.0" }
wally = 	{source = "UpliftGames/wally", 		version = "0.3.1" }
luau-analyze = {source = "JohnnyMorganz/luau-analyze-rojo", version = "0.527.0" }