[package]
name = "nightcycle/node"
description = "A framework useful for creating hierarchical node networks, as well as performing wave function collapse style procedural generation."
version = "1.0.3"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Signal = "nightcycle/signal@^1.0.0"
Maid = "nightcycle/maid@^1.0.2"
Math = "nightcycle/luau-math@1.1.1"

